# Configuración de conexión a MySQL
db.host=localhost
db.port=3306
db.database=mediciones_db
db.user=appuser
db.password=Sierra
db.useSSL=false
db.allowPublicKeyRetrieval=true
db.serverTimezone=UTC
db.characterEncoding=UTF-8